version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql_webprogramming_foodee
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: foodee_app
      MYSQL_USER: baitap
      MYSQL_PASSWORD: 1
    ports:
      - "3308:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_webprogramming_foodee
    environment:
      PMA_HOST: mysql-db
      MYSQL_ROOT_PASSWORD: 1
    ports:
      - "8844:80"
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
